# Strings for translation template for pybackpack.
# Copyright (C) 2008 Andy Price
# This file is distributed under the same license as the pybackpack package.
# Tomoe Sugihara <first dot last at gmail >, 2008.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: 0.5.5\n"
"Report-Msgid-Bugs-To: pybackpack@lists.sucs.org\n"
"POT-Creation-Date: 2010-01-07 22:33+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: Tomoe Sugihara <first dot last at gmail >\n"
"Language-Team: Tomoe Sugihara <first dot last at gmail >\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../pybackpack/actions.py:30
msgid "No read permission on destination directory"
msgstr ""

#: ../pybackpack/actions.py:31
msgid "No write permission on destination directory"
msgstr ""

#: ../pybackpack/actions.py:32
msgid "No execute permission on destionation directory"
msgstr ""

#: ../pybackpack/actions.py:33
msgid ""
"Destination is home directory. This would remove the files in your home "
"directory. Please choose a different location."
msgstr ""

#: ../pybackpack/actions.py:34
msgid "Could not create destination directory"
msgstr ""

#: ../pybackpack/actions.py:35
msgid "Destination directory is not empty"
msgstr ""

#: ../pybackpack/actions.py:104
msgid "Creating destination directory"
msgstr ""

#: ../pybackpack/actions.py:136
msgid "Analyzing source files"
msgstr ""

#: ../pybackpack/actions.py:140
msgid "Destination directory in backup source. Omitting."
msgstr ""

#: ../pybackpack/actions.py:148
msgid "NOTE: Destination directory inside backup set. Omitting."
msgstr ""

#: ../pybackpack/actions.py:160
msgid "Files found"
msgstr ""

#: ../pybackpack/actions.py:164
msgid "Backup source analysis complete."
msgstr "バックアップデータ解析終了。"

#: ../pybackpack/actions.py:172
msgid "Running backup"
msgstr ""

#: ../pybackpack/actions.py:176
msgid "Creating backup"
msgstr ""

#: ../pybackpack/actions.py:189
#, python-format
msgid "Backup failed: %s"
msgstr ""

#: ../pybackpack/actions.py:194 ../pybackpack/actions.py:288
msgid "Backup complete"
msgstr ""

#: ../pybackpack/actions.py:231
msgid "Creating CD image"
msgstr ""

#: ../pybackpack/actions.py:237
msgid "Creating temporary backup"
msgstr ""

#: ../pybackpack/actions.py:245
#, python-format
msgid "Backup failed; could not create CD image %(filename)s: %(error)s\n"
msgstr ""

#: ../pybackpack/actions.py:253
msgid "Writing image to CD/DVD"
msgstr ""

#: ../pybackpack/actions.py:268 ../pybackpack/actions.py:276
msgid "An error occurred while burning the CD."
msgstr "CD/DVD書き込みエラー。"

#: ../pybackpack/actions.py:280
msgid "Cleaning up temporary files"
msgstr ""

#: ../pybackpack/actions.py:302
msgid ""
"\n"
"User"
msgstr ""

#: ../pybackpack/actions.py:304
msgid ""
"\n"
"Host"
msgstr ""

#: ../pybackpack/actions.py:306
msgid ""
"\n"
"Path"
msgstr ""

#: ../pybackpack/actions.py:309
#, python-format
msgid "Missing fields:%s"
msgstr ""

#: ../pybackpack/actions.py:330
msgid "Transferring backup set data"
msgstr ""

#: ../pybackpack/actions.py:333
#, python-format
msgid ""
"Backup completed, but could not copy the backup set data file. You can "
"manually copy this file from\n"
"%(source)s\n"
" to\n"
"%(filepath)s (on host %(hostname)s)"
msgstr ""

#: ../pybackpack/actions.py:338
msgid "Backup completed"
msgstr ""

#: ../pybackpack/actions.py:341
#, python-format
msgid "An error occurred while transferring '%s'."
msgstr ""

#: ../pybackpack/backupsets.py:25 ../pybackpack/backuptool.py:37
#: ../pybackpack/backuptool.py:42 ../pybackpack/gui.py:148
#: ../pybackpack/seteditor.py:127
msgid "home"
msgstr "ホーム"

#: ../pybackpack/backupsets.py:170
#, python-format
msgid "No 'filelist' for %s"
msgstr "%sへのファイルリストは存在しません"

#: ../pybackpack/backupsets.py:185
#, python-format
msgid "Couldn't read in description file: %s"
msgstr "定義ファイル %s　を読み込めません"

#: ../pybackpack/backupsets.py:197
#, python-format
msgid "Couldn't parse %(filename)s fully: %(error)s"
msgstr "%(filename)を解析できません： %(error)s"

#: ../pybackpack/backuptool.py:43
msgid "A complete backup of your home directory."
msgstr "ホームディレクトリ丸ごと"

#: ../pybackpack/filechooser.py:26
msgid "Unable to initialise filechooser"
msgstr "filechooserを初期化できません"

#: ../pybackpack/findfiles.py:21
#, python-format
msgid "Found %s settings."
msgstr "%s の設定を発見。"

#: ../pybackpack/gui.py:59
msgid "New backup set"
msgstr ""

#: ../pybackpack/gui.py:64 ../pybackpack/gui.glade:7
msgid "File Backup Manager"
msgstr ""

#: ../pybackpack/gui.py:101
msgid "Edit a new backup set"
msgstr ""

#: ../pybackpack/gui.py:149
msgid "You cannot delete this set."
msgstr ""

#: ../pybackpack/gui.py:154
#, python-format
msgid ""
"Are you sure you wish to delete the backup set '%s'?\n"
"Deleting this backup set will not delete any previous backups, nor will it "
"affect your ability to restore them."
msgstr ""

#: ../pybackpack/gui.py:169
msgid ""
"There are no remaining backup sets.\n"
"To create a new backup set, click 'New'."
msgstr ""

#: ../pybackpack/gui.py:172
msgid "Select a backup set from the list on the left."
msgstr ""

#: ../pybackpack/gui.py:193
msgid "Selected backup set cannot be edited."
msgstr ""

#: ../pybackpack/gui.py:233
msgid "Burning CD/DVD"
msgstr ""

#: ../pybackpack/gui.py:235
msgid "Waiting for CD/DVD"
msgstr ""

#: ../pybackpack/gui.py:243
#, python-format
msgid "Starting backup of '%s' to CD\n"
msgstr "「%s」のCDへのバックアップを開始\n"

#: ../pybackpack/gui.py:246
msgid "No CD burners detected."
msgstr ""

#: ../pybackpack/gui.py:247
msgid "Backup failed; no CD burners detected.\n"
msgstr ""

#: ../pybackpack/gui.py:264 ../pybackpack/gui.py:356
msgid ""
"The destination directory is not empty and it doesn't look like a previous "
"backup. Continue?"
msgstr ""

#: ../pybackpack/gui.py:329
msgid "Please select a location to back up to."
msgstr ""

#: ../pybackpack/gui.py:331
#, python-format
msgid "Starting backup of '%(backup)s' to '%(destination)s'\n"
msgstr "バックアップセット%(backup)sの%(destination)sへのバックアップを開始\n"

#: ../pybackpack/gui.py:333
msgid "Starting backup"
msgstr ""

#: ../pybackpack/gui.py:335
#, python-format
msgid "Please connect and mount the device for '%s'"
msgstr "デバイスを接続し「%s」へマウントしてください"

#: ../pybackpack/gui.py:339
msgid "Backup cancelled by user.\n"
msgstr "バックアップはユーザによりキャンセルされました。\n"

#: ../pybackpack/gui.py:348
msgid "Checking destination directory"
msgstr ""

#: ../pybackpack/gui.py:364 ../pybackpack/gui.py:406
msgid "Backup completed.\n"
msgstr "バックアップ完了。\n"

#: ../pybackpack/gui.py:391
#, python-format
msgid "Starting backup of '%(backup)s' to '%(hostname)s'"
msgstr " バックアップセット'%(backup)s'の'%(hostname)s'へのバックアップ開始"

#: ../pybackpack/gui.py:420
msgid "Select a backup destination"
msgstr ""

#: ../pybackpack/gui.py:439
msgid "Select a default remote location to backup to"
msgstr ""

#: ../pybackpack/gui.py:442 ../pybackpack/seteditor.py:267
msgid "Select a default remote location to backup to."
msgstr ""

#: ../pybackpack/gui.py:459
msgid "Select a location to restore from"
msgstr "リストア元の場所を選択します"

#: ../pybackpack/gui.py:487
msgid "Only sftp:// and file:// locations are supported."
msgstr ""

#: ../pybackpack/gui.py:491
msgid "Click the 'refresh' button to read this backup set"
msgstr "「更新」ボタンをクリックしてバックアップセット情報を読み込みます。"

#: ../pybackpack/gui.py:501 ../pybackpack/gui.py:644
#, python-format
msgid "This data will be restored to %s"
msgstr "このデータは %s へリストアされます"

#: ../pybackpack/gui.py:531
#, python-format
msgid "Starting restore operation from '%s'\n"
msgstr ""

#: ../pybackpack/gui.py:532
msgid "Starting restore operation..."
msgstr "リストア開始中..."

#: ../pybackpack/gui.py:541
#, python-format
msgid "An error occurred when trying to create '%s'."
msgstr ""

#: ../pybackpack/gui.py:542
#, python-format
msgid "Restore failed; could not create destination path '%s'\n"
msgstr ""

#: ../pybackpack/gui.py:547
#, python-format
msgid "You don't have permission to write to '%s'.\n"
msgstr ""

#: ../pybackpack/gui.py:552
#, python-format
msgid "There are already files in '%s'."
msgstr "既に「%s」にファイルが存在します。"

#: ../pybackpack/gui.py:553
msgid ""
"If you restore your backup to this location, these files will be erased "
"permanently."
msgstr "この場所にリストアを実行すると、それらのファイルは完全に消去されます。"

#: ../pybackpack/gui.py:554
msgid "Are you sure you want to do this?"
msgstr "本当に実行しますか？"

#: ../pybackpack/gui.py:559
msgid "Checking restore source..."
msgstr ""

#: ../pybackpack/gui.py:564
msgid "Copying from CD..."
msgstr ""

#: ../pybackpack/gui.py:565
#, python-format
msgid "Copying from CD (%(count)d files) to %(destination)s."
msgstr ""

#: ../pybackpack/gui.py:576
#, python-format
msgid ""
"Couldn't copy CD from '%(cdpath)s' to '%(destination)s'.\n"
"Please check there is enough disk space and try again."
msgstr ""

#: ../pybackpack/gui.py:579
msgid "Restore failed; could not copy CD to temporary location.\n"
msgstr ""

#: ../pybackpack/gui.py:581
msgid "CD copy finished."
msgstr ""

#: ../pybackpack/gui.py:582
msgid "Restoring files..."
msgstr "リストア実行中..."

#: ../pybackpack/gui.py:590
msgid "Restoring files."
msgstr ""

#: ../pybackpack/gui.py:599
#, python-format
msgid "An error occurred whilst restoring from '%s'."
msgstr ""

#: ../pybackpack/gui.py:603
#, python-format
msgid "Cleaning up %s..."
msgstr ""

#: ../pybackpack/gui.py:604
#, python-format
msgid "Cleaning up temporary files from %s."
msgstr ""

#: ../pybackpack/gui.py:608
#, python-format
msgid "Cleaning up temporary files failed, please manually delete %s"
msgstr ""

#: ../pybackpack/gui.py:611
msgid "Restore succeeded.\n"
msgstr ""

#: ../pybackpack/gui.py:613
#, python-format
msgid ""
"Restore succeeded.\n"
"The restored files are in 'restored_files/%s' in your home directory."
msgstr ""
"リストアが成功しました。\n"
"リストアファイルはホームディレクトリの「restored_files/%s」になります。"

#: ../pybackpack/gui.py:657
msgid ""
"An error occurred while reading the remote backup set information.\n"
"Please check the username, host name and path that you have entered and try "
"again."
msgstr ""
"リモートのバックアップセットの読み込み中にエラーが発生しました。ユーザ名、ホ"
"スト名、パス名を確認し再度実行してください。"

#: ../pybackpack/gui.py:675
#, python-format
msgid "%s is a tool for backing up user data for the GNOME Desktop"
msgstr ""
"%s はGNOMEデスクトップ環境のためのユーザーデータバックアップツールです。"

#: ../pybackpack/gui.py:697
msgid "Copying from CD:"
msgstr ""

#: ../pybackpack/gui.py:708
#, python-format
msgid "Could not remove '%(filename)s': %(error_msg)s"
msgstr "'%(filename)s': %(error_msg)s　を削除できませんでした。"

#: ../pybackpack/gui.py:712
msgid "Operation failed.\n"
msgstr "実行失敗。\n"

#: ../pybackpack/gui.py:717
msgid "Restore aborted, no files were changed.\n"
msgstr "変更ファイルがないためリストア停止。\n"

#: ../pybackpack/rdiff_interface.py:178
msgid "Error:"
msgstr "エラー："

#: ../pybackpack/rdiff_interface.py:179
msgid "rdiff-backup version: "
msgstr "rdiff-backup バージョン: "

#: ../pybackpack/rdiff_interface.py:180
msgid "version:"
msgstr "バージョン："

#: ../pybackpack/seteditor.py:26
msgid "Unable to start the backup set editor"
msgstr "バックアップセットの編集に失敗しました"

#: ../pybackpack/seteditor.py:56
msgid "Path"
msgstr "パス"

#: ../pybackpack/seteditor.py:86 ../pybackpack/seteditor.glade:7
msgid "Create New Backup Set"
msgstr "新しいバックアップセットを作成します"

#: ../pybackpack/seteditor.py:105 ../pybackpack/seteditor.glade:940
msgid "0 items"
msgstr "0 個"

#: ../pybackpack/seteditor.py:176
#, python-format
msgid "Editing backup set '%s'"
msgstr "バックアップセット　'%s'　編集中"

#: ../pybackpack/seteditor.py:182
msgid "Editing new backup set"
msgstr ""

#: ../pybackpack/seteditor.py:218
#, python-format
msgid ""
"A set with the name '%s' already exists.\n"
"You can either enter a new name in the text box above, or overwrite the "
"existing set."
msgstr ""
"'%s'という名前のバックアップセットは既に存在します。\n"
"上のテキストボックスに別の名前を入力するか、既存のセットを上書きするかを選択"
"可能です。"

#: ../pybackpack/seteditor.py:250
#, python-format
msgid "Add Files/Folders to '%s'"
msgstr ""

#: ../pybackpack/seteditor.py:256
msgid "You cannot create an empty backup set."
msgstr "空のバックアップセットは作成できません。"

#: ../pybackpack/seteditor.py:283
msgid "Select a default destination"
msgstr ""

#: ../pybackpack/seteditor.py:318
#, python-format
msgid "ERROR: Couldn't write new set %(name)s: %(error)s"
msgstr "エラー：　新規セット %(name)s: %(error)s の作成に失敗"

#: ../pybackpack/seteditor.py:332 ../pybackpack/seteditor.py:348
#: ../pybackpack/seteditor.py:359
msgid "1 item"
msgstr "1 個"

#: ../pybackpack/seteditor.py:334 ../pybackpack/seteditor.py:350
#: ../pybackpack/seteditor.py:361
#, python-format
msgid "%d items"
msgstr "%d 個"

#: ../pybackpack/seteditor.py:369
msgid ""
"No CD burners available, because you do not have the python module "
"braseromedia."
msgstr ""

#: ../pybackpack/statuswindow.py:20
msgid "Failed to initialise status window."
msgstr "ステータスウィンドウの初期化に失敗しました。"

#: ../pybackpack/filechooser.glade:6
msgid "Select backup destination"
msgstr "保存先を選択"

#: ../pybackpack/gui.glade:20
msgid "_File"
msgstr "ファイル"

#: ../pybackpack/gui.glade:26
msgid "New _Backup Set..."
msgstr "新規バックアップセット"

#: ../pybackpack/gui.glade:42
msgid "_Restore From..."
msgstr "リストア"

#: ../pybackpack/gui.glade:78
msgid "_View"
msgstr "ビュー"

#: ../pybackpack/gui.glade:84
msgid "_Status Window"
msgstr "ステータスウィンドウ"

#: ../pybackpack/gui.glade:104
msgid "_Help"
msgstr "ヘルプ"

#: ../pybackpack/gui.glade:158
msgid ""
"To backup your entire home directory to a blank CD or DVD, click the 'Go' "
"button. This backup will include all of your personal settings, documents, e-"
"mails and any other readable files stored in your home directory. For more "
"options or to backup a different set of files, click the tab labelled "
"'Backup' above."
msgstr ""
"「Go」ボタンをクリックすると、ホームディレクトリー全体をCDやDVDにバックアップ"
"します。このバックアップは、すべての個人設定、ドキュメント、emailを含むその他"
"すべてのホームディレクトリ上のファイルを対象とします。より細かなオプションを"
"指定するには、上の「バックアップ」タブをクリックしてください。"

#: ../pybackpack/gui.glade:196
msgid "Go"
msgstr ""

#: ../pybackpack/gui.glade:221
msgid "<b>Home Directory Backup</b>"
msgstr "<b>ホームディレクトリーのバックアップ</b>"

#: ../pybackpack/gui.glade:247
msgid "Home"
msgstr "ホーム"

#: ../pybackpack/gui.glade:336 ../pybackpack/gui.glade:1078
#: ../pybackpack/seteditor.glade:144 ../pybackpack/seteditor.glade:1052
msgid "Description:"
msgstr "説明:"

#: ../pybackpack/gui.glade:366
msgid "<b>Backup set</b>"
msgstr ""

#: ../pybackpack/gui.glade:396 ../pybackpack/seteditor.glade:632
msgid ""
"Local File System\n"
"CD/DVD\n"
"Remote Host (SSH)"
msgstr ""
"ローカルファイルシステム\n"
"CD/DVD\n"
"リモートホスト (SSH)"

#: ../pybackpack/gui.glade:421 ../pybackpack/seteditor.glade:1090
msgid "Destination:"
msgstr "保存先"

#: ../pybackpack/gui.glade:475
msgid "Removable media"
msgstr "リムーバブルメディア（外付けメディア）"

#: ../pybackpack/gui.glade:497 ../pybackpack/seteditor.glade:403
msgid "local"
msgstr ""

#: ../pybackpack/gui.glade:529 ../pybackpack/seteditor.glade:466
msgid "cd"
msgstr ""

#: ../pybackpack/gui.glade:548 ../pybackpack/seteditor.glade:485
msgid "Username:"
msgstr "ユーザ名"

#: ../pybackpack/gui.glade:559 ../pybackpack/seteditor.glade:496
msgid "Host:"
msgstr "ホスト名"

#: ../pybackpack/gui.glade:572 ../pybackpack/seteditor.glade:509
msgid "Path:"
msgstr "パス"

#: ../pybackpack/gui.glade:658 ../pybackpack/seteditor.glade:600
msgid "ssh"
msgstr ""

#: ../pybackpack/gui.glade:679
msgid "<b>Destination</b>"
msgstr ""

#: ../pybackpack/gui.glade:698
msgid "Show details"
msgstr "詳細を表示"

#: ../pybackpack/gui.glade:743
msgid "_Backup"
msgstr "バックアップ"

#: ../pybackpack/gui.glade:787
msgid "Backup"
msgstr "バックアップ"

#: ../pybackpack/gui.glade:822
msgid "Local"
msgstr "ローカル"

#: ../pybackpack/gui.glade:838
msgid "Remote (SSH)"
msgstr "リモート (SSH)"

#: ../pybackpack/gui.glade:860
msgid "Username"
msgstr "ユーザ名"

#: ../pybackpack/gui.glade:862
msgid "username"
msgstr "ユーザ名"

#: ../pybackpack/gui.glade:876
msgid "Remote Hostname"
msgstr "リモートホスト名"

#: ../pybackpack/gui.glade:878
msgid "host"
msgstr "ホスト名"

#: ../pybackpack/gui.glade:894
msgid "Refresh"
msgstr ""

#: ../pybackpack/gui.glade:972
msgid "<b>Location to restore from:</b>"
msgstr "<b>リストア元の場所:</b>"

#: ../pybackpack/gui.glade:1009
msgid "Restore as of:"
msgstr "リストア時点:"

#: ../pybackpack/gui.glade:1052
msgid ""
"Read-only\n"
"source"
msgstr ""

#: ../pybackpack/gui.glade:1092 ../pybackpack/seteditor.glade:668
#: ../pybackpack/seteditor.glade:1038
msgid "Name:"
msgstr "セット名:"

#: ../pybackpack/gui.glade:1173
msgid "_Restore"
msgstr "リストア"

#: ../pybackpack/gui.glade:1214
msgid "Restore"
msgstr "リストア"

#: ../pybackpack/seteditor.glade:21
msgid "New Backup Set"
msgstr "バックアップセット作成"

#: ../pybackpack/seteditor.glade:22
msgid ""
"This guide will walk you through the steps\n"
"needed to create a group of files that are\n"
"backed up, known as a 'backup set'.\n"
"\n"
"Click 'Forward' to begin."
msgstr ""
"これからバックアップセットと呼ばれる、\n"
"バックアップ対象ファイルのセットを作成します。\n"
"「進む」をクリックし開始して下さい。"

#: ../pybackpack/seteditor.glade:32
msgid "Backup Set Name"
msgstr "バックアップセット情報"

#: ../pybackpack/seteditor.glade:51
msgid ""
"Enter a name for the new backup set.\n"
"e.g. \"e-mail\" for a set containing e-mail messages and settings."
msgstr ""

#: ../pybackpack/seteditor.glade:70
msgid "Enter some descriptive text for this new set."
msgstr ""

#: ../pybackpack/seteditor.glade:95
msgid ""
"A set with the name '' already exists.\n"
"You can either enter a new name in the text box above, or overwrite the "
"existing set."
msgstr ""

#: ../pybackpack/seteditor.glade:108
msgid "Overwrite existing set"
msgstr "既存のセットを上書き"

#: ../pybackpack/seteditor.glade:126
msgid "<b>Warning</b>"
msgstr "<b>注意</b>"

#: ../pybackpack/seteditor.glade:167
msgid ""
"You didn't enter a name for this backup set.\n"
"Please enter a name in the relevant field above and click 'Forward' to "
"continue."
msgstr ""
"バックアップセットの名前が指定されていません適当な名前を入力し「進む」をク"
"リックして進んで下さい。"

#: ../pybackpack/seteditor.glade:183 ../pybackpack/seteditor.glade:227
#: ../pybackpack/seteditor.glade:270
msgid "<b>Error</b>"
msgstr "<b>エラー</b>"

#: ../pybackpack/seteditor.glade:211
msgid ""
"You selected to backup to a remote host, but didn't provide enough "
"information.\n"
"Please enter your username, remote host, and the absolute path where the "
"files should be backed up to."
msgstr ""
"バックアップ先にリモートホストが選択されましたが、十分な情報が入力されていま"
"せん。ユーザ名、リモートホスト名、保存先の絶対パスを入力してください。"

#: ../pybackpack/seteditor.glade:255
msgid ""
"You do not have appropriate permissions to use the CD/DVD burner you have "
"selected '%s'."
msgstr "選択された CD/DVD作成ドライブ('%s')を利用する権限がありません。"

#: ../pybackpack/seteditor.glade:308
msgid "Default Destination:"
msgstr "デフォルト保存先："

#: ../pybackpack/seteditor.glade:335
msgid ""
"[Optional]\n"
"Select a default location for this set to be backed up to."
msgstr ""
"[オプション]\n"
"このバックアップセットのデフォルト保存先を選択。"

#: ../pybackpack/seteditor.glade:346
msgid "This is a removable device"
msgstr "リムーバブルメディア（外付けメディア）"

#: ../pybackpack/seteditor.glade:416
msgid "Select which CD/DVD Burner to use:"
msgstr "書き込み可能なCD/DVDドライブを選択してください"

#: ../pybackpack/seteditor.glade:427
msgid "CD/DVD Burner:"
msgstr "CD/DVD作成ドライブ:"

#: ../pybackpack/seteditor.glade:620
msgid "Destination type:"
msgstr "保存先タイプ"

#: ../pybackpack/seteditor.glade:658
msgid ""
"This new backup set needs to be given a name, and optionally, a description "
"and a default destination for backups made from this set."
msgstr ""
"この新規バックアップセットは名前、オプションとして説明とデフォルト保存先を設"
"定する必要があります。"

#: ../pybackpack/seteditor.glade:679
msgid "Click 'Forward' to continue."
msgstr "「進む」をクリックして次へ。"

#: ../pybackpack/seteditor.glade:707
msgid ""
"To add a file/folder to the backup set, select it in the file chooser and "
"click 'Add to set'."
msgstr "ファイル/ディレクトリをバックアップセットに追加します。"

#: ../pybackpack/seteditor.glade:737
msgid "Show hidden files"
msgstr ""

#: ../pybackpack/seteditor.glade:775
msgid "Exclude from set"
msgstr "セットから除外"

#: ../pybackpack/seteditor.glade:824
msgid "Include in set"
msgstr "セットに追加"

#: ../pybackpack/seteditor.glade:912
msgid "Remove from set"
msgstr ""

#: ../pybackpack/seteditor.glade:963
msgid "Summary"
msgstr "内容確認"

#: ../pybackpack/seteditor.glade:980
msgid ""
"This page gives you an opportunity to review the backup set before it is "
"saved.\n"
"To make any changes, click 'Back'."
msgstr ""
"以下の内容を再確認してください。変更を加える場合は'戻る'をクリックしてくださ"
"い。"

#: ../pybackpack/seteditor.glade:1011
msgid "To proceed and save this backup set, click 'Forward'."
msgstr "この内容でよろしければ、「進む」をクリックして下さい。"

#: ../pybackpack/seteditor.glade:1024
msgid "Files:"
msgstr "ファイル一覧："

#: ../pybackpack/seteditor.glade:1120
msgid "Finished!"
msgstr "完了！"

#: ../pybackpack/seteditor.glade:1121
msgid "You're all done! Congratulations."
msgstr "バックアップセットの作成が完了しました！"

#: ../pybackpack/statuswindow.glade:8
msgid "Backup Status Window"
msgstr "バックアップステータスウィンドウ"

#: ../pybackpack/statuswindow.glade:48
msgid "<b>Status</b>"
msgstr "<b>ステータス</b>"

#~ msgid "Backup Sets"
#~ msgstr "バックアップセット"

#~ msgid "To begin, select a backup set from the list on the left."
#~ msgstr ""
#~ "左のリストからバックアップセットを選択し、バックアップを開始します。"

#~ msgid "<b>Description</b>"
#~ msgstr "<b>説明</b>"

#~ msgid ""
#~ "No CD burners available, because you do not have the python module "
#~ "nautilusburn."
#~ msgstr ""
#~ "pythonモジュール「nautilusburn.」がないため、CDドライブが利用できません。"

#~ msgid "No CD burners were detected on your system."
#~ msgstr "書き込み可能なCD/DVDドライブがシステム内に見つかりません。"

#~ msgid "Select which CD burner to use:"
#~ msgstr "書き込み可能なCD/DVDドライブを選択します："

#~ msgid "Please insert a blank CD into %s"
#~ msgstr "空のメディアをドライブ「%s」へ挿入して下さい。"

#~ msgid "To restore your data, select the folder that contains the backup."
#~ msgstr "バックアップデータの場所を指定しリストアします"

#~ msgid "Location is:"
#~ msgstr "リストア元の場所は："

#~ msgid "_Quit"
#~ msgstr "終了"

#~ msgid "_About..."
#~ msgstr "このプログラムについて"

#~ msgid "Show status window"
#~ msgstr "ステータスウィンドウを表示する"

#~ msgid "Add Files/Folders to ''"
#~ msgstr "ファイル/ディレクトリをバックアップセットに追加''"

#~ msgid ""
#~ "Unable to start %(progname)s:\n"
#~ "%(error)s"
#~ msgstr ""
#~ "%(progname):のスタートに失敗：\n"
#~ "%(error)s"

#~ msgid "Starting backup..."
#~ msgstr "バックアップ開始中..."

#~ msgid "Creating backup..."
#~ msgstr "バックアップデータ作成中..."

#~ msgid "Creating temporary backup in %s"
#~ msgstr "一時バックアップファイルを「%s」へ作成中"

#~ msgid "Ready."
#~ msgstr "待機中"

#~ msgid "Creating CD image..."
#~ msgstr "CDイメージ作成中..."

#~ msgid "Creating CD image."
#~ msgstr "CDイメージ作成中。"

#~ msgid "Preparing to burn CD..."
#~ msgstr "CD/DVD作成準備中..."

#~ msgid "Starting to burn CD."
#~ msgstr "CD/DVDへの書き込み開始。"

#~ msgid "Backup failed; CD burn failed.\n"
#~ msgstr "バックアップ失敗。CD/DVDへの書き込みが失敗。\n"

#~ msgid "Backup completed successfully."
#~ msgstr "バックアップが正常に終了しました。"

#~ msgid "Running rdiff-backup"
#~ msgstr "rdiff-backup 実行中"

#~ msgid "Running rdiff-backup."
#~ msgstr "rdiff-backup 実行中"

#~ msgid "Backing up to %s"
#~ msgstr "%s へバックアップ中"

#~ msgid "Analysing backup source..."
#~ msgstr "バックアップデータを解析しています。"

#~ msgid "Analysing backup source."
#~ msgstr "バックアップデータを解析しています。"

#~ msgid "Finished."
#~ msgstr "完了。"

#~ msgid "Copying from CD - current file:"
#~ msgstr "CDからコピー中 - 現在のファイル:"

#~ msgid "Creating backup... (Approx %d%% done)"
#~ msgstr "バックアップ作成中... （およそ %d%% 完了)"

#~ msgid "Please e-mail the contents of this text box to:"
#~ msgstr "テキストボックス内の内容を次のアドレスにe-mailしてください："

#~ msgid "Select a default location to backup to"
#~ msgstr "デフォルトの保存先を選択"

#~ msgid "Foo"
#~ msgstr "フォー!"
