# Strings for translation template for pybackpack.
# Copyright (C) 2009 Andy Price
# This file is distributed under the same license as the pybackpack package.
# Lex V. Ross <lross@mail.ru>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: pybackpack 0.5.7\n"
"Report-Msgid-Bugs-To: pybackpack@lists.sucs.org\n"
"POT-Creation-Date: 2010-01-07 22:33+0000\n"
"PO-Revision-Date: 2009-10-29 17:45+0300\n"
"Last-Translator: Lex V. Ross <lross@mail.ru>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../pybackpack/actions.py:30
msgid "No read permission on destination directory"
msgstr "Нет прав на чтение папки назначения"

#: ../pybackpack/actions.py:31
msgid "No write permission on destination directory"
msgstr "Нет прав на запись в папку назначения"

#: ../pybackpack/actions.py:32
msgid "No execute permission on destionation directory"
msgstr "Нет прав на выполнение папки назначения"

#: ../pybackpack/actions.py:33
msgid ""
"Destination is home directory. This would remove the files in your home "
"directory. Please choose a different location."
msgstr ""
"В качестве назначения указана домашняя папка, что приведет к удалению файлов "
"из вашей домашней папки. Пожалуйста, выберите другую папку."

#: ../pybackpack/actions.py:34
msgid "Could not create destination directory"
msgstr "Не удалось создать папку назначения"

#: ../pybackpack/actions.py:35
msgid "Destination directory is not empty"
msgstr "Папка назначения непуста"

#: ../pybackpack/actions.py:104
msgid "Creating destination directory"
msgstr "Создается папка назначения"

#: ../pybackpack/actions.py:136
msgid "Analyzing source files"
msgstr "Проверяются исходные файлы"

#: ../pybackpack/actions.py:140
msgid "Destination directory in backup source. Omitting."
msgstr "Папка назначения в составе файлов для копирования. Пропускаю."

#: ../pybackpack/actions.py:148
msgid "NOTE: Destination directory inside backup set. Omitting."
msgstr "ВНИМАНИЕ: Папка назначения внутри набора резервирования. Пропускаю."

#: ../pybackpack/actions.py:160
msgid "Files found"
msgstr "Найдены файлы"

#: ../pybackpack/actions.py:164
msgid "Backup source analysis complete."
msgstr "Завершена проверка исходных данных."

#: ../pybackpack/actions.py:172
msgid "Running backup"
msgstr "Копирование файлов"

#: ../pybackpack/actions.py:176
msgid "Creating backup"
msgstr "Создается резервная копия"

#: ../pybackpack/actions.py:189
#, python-format
msgid "Backup failed: %s"
msgstr "Ошибка резервного копирования: %s"

#: ../pybackpack/actions.py:194 ../pybackpack/actions.py:288
msgid "Backup complete"
msgstr "Резервное копирование завершено"

#: ../pybackpack/actions.py:231
msgid "Creating CD image"
msgstr "Создается образ компакт-диска"

#: ../pybackpack/actions.py:237
msgid "Creating temporary backup"
msgstr "Создание временной резервной копии"

#: ../pybackpack/actions.py:245
#, python-format
msgid "Backup failed; could not create CD image %(filename)s: %(error)s\n"
msgstr ""
"Ошибка резервного копирования; не могу создать образ диска %(filename)s: %"
"(error)s\n"

#: ../pybackpack/actions.py:253
msgid "Writing image to CD/DVD"
msgstr "Записываю образ на CD/DVD"

#: ../pybackpack/actions.py:268 ../pybackpack/actions.py:276
msgid "An error occurred while burning the CD."
msgstr "При записи компакт-диска произошла ошибка."

#: ../pybackpack/actions.py:280
msgid "Cleaning up temporary files"
msgstr "Удаляются временные файлы"

#: ../pybackpack/actions.py:302
msgid ""
"\n"
"User"
msgstr ""
"\n"
"Имя пользователя"

#: ../pybackpack/actions.py:304
msgid ""
"\n"
"Host"
msgstr ""
"\n"
"Узел"

#: ../pybackpack/actions.py:306
msgid ""
"\n"
"Path"
msgstr ""
"\n"
"Путь"

#: ../pybackpack/actions.py:309
#, python-format
msgid "Missing fields:%s"
msgstr "Не заполнены поля:%s"

#: ../pybackpack/actions.py:330
msgid "Transferring backup set data"
msgstr "Перемещаются данные набора резервирования"

#: ../pybackpack/actions.py:333
#, python-format
msgid ""
"Backup completed, but could not copy the backup set data file. You can "
"manually copy this file from\n"
"%(source)s\n"
" to\n"
"%(filepath)s (on host %(hostname)s)"
msgstr ""
"Резервное копирование завершено, однако не удалось скопировать файл данных "
"набора резервирования. Вы можете скопировать его вручную из\n"
"%(source)s\n"
" в\n"
"%(filepath)s (на компьютере %(hostname)s)"

#: ../pybackpack/actions.py:338
msgid "Backup completed"
msgstr "Резервное копирование завершено"

#: ../pybackpack/actions.py:341
#, python-format
msgid "An error occurred while transferring '%s'."
msgstr "Произошла ошибка при перемещении '%s'."

#: ../pybackpack/backupsets.py:25 ../pybackpack/backuptool.py:37
#: ../pybackpack/backuptool.py:42 ../pybackpack/gui.py:148
#: ../pybackpack/seteditor.py:127
msgid "home"
msgstr "Домашняя папка"

#: ../pybackpack/backupsets.py:170
#, python-format
msgid "No 'filelist' for %s"
msgstr "Отсутствует 'filelist' для %s"

#: ../pybackpack/backupsets.py:185
#, python-format
msgid "Couldn't read in description file: %s"
msgstr "Не удалось прочитать файл описания: %s"

#: ../pybackpack/backupsets.py:197
#, python-format
msgid "Couldn't parse %(filename)s fully: %(error)s"
msgstr "Не удалось полностью обработать %(filename)s: %(error)s"

#: ../pybackpack/backuptool.py:43
msgid "A complete backup of your home directory."
msgstr "Полная резервная копия вашей домашней папки"

#: ../pybackpack/filechooser.py:26
msgid "Unable to initialise filechooser"
msgstr "Не удалось инициализировать диалог выбора файлов"

#: ../pybackpack/findfiles.py:21
#, python-format
msgid "Found %s settings."
msgstr "Найдено %s настроек."

#: ../pybackpack/gui.py:59
msgid "New backup set"
msgstr ""

#: ../pybackpack/gui.py:64 ../pybackpack/gui.glade:7
msgid "File Backup Manager"
msgstr "Резервное копирование файлов"

#: ../pybackpack/gui.py:101
msgid "Edit a new backup set"
msgstr ""

#: ../pybackpack/gui.py:149
msgid "You cannot delete this set."
msgstr "Вы не можете удалить этот набор."

#: ../pybackpack/gui.py:154
#, python-format
msgid ""
"Are you sure you wish to delete the backup set '%s'?\n"
"Deleting this backup set will not delete any previous backups, nor will it "
"affect your ability to restore them."
msgstr ""
"Вы уверены, что хотите удалить набор резервирования '%s'?\n"
"Удаление набора не приведет к удалению созданных ранее резервных копий и не "
"повлияет на возможность их восстановления."

#: ../pybackpack/gui.py:169
msgid ""
"There are no remaining backup sets.\n"
"To create a new backup set, click 'New'."
msgstr ""
"Наборов резервирования больше не осталось.\n"
"Для создания нового набора нажмите 'Создать'."

#: ../pybackpack/gui.py:172
msgid "Select a backup set from the list on the left."
msgstr "Выберите набор резервирования из списка слева."

#: ../pybackpack/gui.py:193
msgid "Selected backup set cannot be edited."
msgstr "Выбранный набор резервирования нельзя редактировать."

#: ../pybackpack/gui.py:233
msgid "Burning CD/DVD"
msgstr "Записываю CD/DVD"

#: ../pybackpack/gui.py:235
msgid "Waiting for CD/DVD"
msgstr "Жду CD/DVD"

#: ../pybackpack/gui.py:243
#, python-format
msgid "Starting backup of '%s' to CD\n"
msgstr "Начинаю копирование '%s' на CD\n"

#: ../pybackpack/gui.py:246
msgid "No CD burners detected."
msgstr "Не найдены пишущие CD приводы."

#: ../pybackpack/gui.py:247
msgid "Backup failed; no CD burners detected.\n"
msgstr "Ошибка резервного копирования; не обнаружено пишущих CD-приводов.\n"

#: ../pybackpack/gui.py:264 ../pybackpack/gui.py:356
msgid ""
"The destination directory is not empty and it doesn't look like a previous "
"backup. Continue?"
msgstr ""
"Папка назначения непуста и не похожа на предыдущую резервную копию. "
"Продолжать?"

#: ../pybackpack/gui.py:329
msgid "Please select a location to back up to."
msgstr "Пожалуйста, выберите папку назначения для резервного копирования."

#: ../pybackpack/gui.py:331
#, python-format
msgid "Starting backup of '%(backup)s' to '%(destination)s'\n"
msgstr "Начинаю резервное копирование '%(backup)s' в '%(destination)s'\n"

#: ../pybackpack/gui.py:333
msgid "Starting backup"
msgstr "Начинаю резервное копирование"

#: ../pybackpack/gui.py:335
#, python-format
msgid "Please connect and mount the device for '%s'"
msgstr "Пожалуйста, подсоедините и смонтируйте устройство для '%s'"

#: ../pybackpack/gui.py:339
msgid "Backup cancelled by user.\n"
msgstr "Резервное копирование прервано пользователем.\n"

#: ../pybackpack/gui.py:348
msgid "Checking destination directory"
msgstr "Проверяю папку назначения"

#: ../pybackpack/gui.py:364 ../pybackpack/gui.py:406
msgid "Backup completed.\n"
msgstr "Резервное копирование завершено.\n"

#: ../pybackpack/gui.py:391
#, python-format
msgid "Starting backup of '%(backup)s' to '%(hostname)s'"
msgstr "Начинаю резервное копирование '%(backup)s' в '%(hostname)s'"

#: ../pybackpack/gui.py:420
msgid "Select a backup destination"
msgstr "Выберите назначение для резервной копии"

#: ../pybackpack/gui.py:439
msgid "Select a default remote location to backup to"
msgstr "Выберите удаленный путь резервной копии по умолчанию"

#: ../pybackpack/gui.py:442 ../pybackpack/seteditor.py:267
msgid "Select a default remote location to backup to."
msgstr "Выберите удаленный путь резервной копии по умолчанию."

#: ../pybackpack/gui.py:459
msgid "Select a location to restore from"
msgstr "Выберите место, из которого восстановить резервную копию"

#: ../pybackpack/gui.py:487
msgid "Only sftp:// and file:// locations are supported."
msgstr "Поддерживаются только пути sftp:// и file://"

#: ../pybackpack/gui.py:491
msgid "Click the 'refresh' button to read this backup set"
msgstr "Чтобы прочитать этот набор резервирования, нажмите кнопку 'обновить'."

#: ../pybackpack/gui.py:501 ../pybackpack/gui.py:644
#, python-format
msgid "This data will be restored to %s"
msgstr "Данные будут восстановлены в %s"

#: ../pybackpack/gui.py:531
#, python-format
msgid "Starting restore operation from '%s'\n"
msgstr "Начинаю операцию восстановления из '%s'\n"

#: ../pybackpack/gui.py:532
msgid "Starting restore operation..."
msgstr "Начинаю операцию восстановления..."

#: ../pybackpack/gui.py:541
#, python-format
msgid "An error occurred when trying to create '%s'."
msgstr "Ошибка при попытке создания '%s'."

#: ../pybackpack/gui.py:542
#, python-format
msgid "Restore failed; could not create destination path '%s'\n"
msgstr "Ошибка восстановления: не удалось создать путь назначения '%s'\n"

#: ../pybackpack/gui.py:547
#, python-format
msgid "You don't have permission to write to '%s'.\n"
msgstr "У вас нет прав на запись в '%s'.\n"

#: ../pybackpack/gui.py:552
#, python-format
msgid "There are already files in '%s'."
msgstr "В '%s' уже есть файлы."

#: ../pybackpack/gui.py:553
msgid ""
"If you restore your backup to this location, these files will be erased "
"permanently."
msgstr ""
"Если вы восстановите сюда резервную копию, то эти файлы будут утеряны "
"безвозвратно."

#: ../pybackpack/gui.py:554
msgid "Are you sure you want to do this?"
msgstr "Вы уверены, что хотите этого?"

#: ../pybackpack/gui.py:559
msgid "Checking restore source..."
msgstr "Проверка источника восстановления..."

#: ../pybackpack/gui.py:564
msgid "Copying from CD..."
msgstr "Копирование с CD..."

#: ../pybackpack/gui.py:565
#, python-format
msgid "Copying from CD (%(count)d files) to %(destination)s."
msgstr "Копирование с CD (%(count)d файлов) в %(destination)s."

#: ../pybackpack/gui.py:576
#, python-format
msgid ""
"Couldn't copy CD from '%(cdpath)s' to '%(destination)s'.\n"
"Please check there is enough disk space and try again."
msgstr ""
"Не удалось скопировать CD из '%(cdpath)s' в '%(destination)s'.\n"
"Пожалуйста, проверьте, чтобы на диске было достаточно свободного места и "
"повторите попытку."

#: ../pybackpack/gui.py:579
msgid "Restore failed; could not copy CD to temporary location.\n"
msgstr ""
"Ошибка восстановления: не удалось скопировать CD во временный каталог.\n"

#: ../pybackpack/gui.py:581
msgid "CD copy finished."
msgstr "Копирование CD завершено."

#: ../pybackpack/gui.py:582
msgid "Restoring files..."
msgstr "Восстанавлюваются файлы..."

#: ../pybackpack/gui.py:590
msgid "Restoring files."
msgstr "Восстанавливаю файлы."

#: ../pybackpack/gui.py:599
#, python-format
msgid "An error occurred whilst restoring from '%s'."
msgstr "Ошибка при восстановлении из '%s'."

#: ../pybackpack/gui.py:603
#, python-format
msgid "Cleaning up %s..."
msgstr "Очищаю %s..."

#: ../pybackpack/gui.py:604
#, python-format
msgid "Cleaning up temporary files from %s."
msgstr "Удаляются временные файлы из %s."

#: ../pybackpack/gui.py:608
#, python-format
msgid "Cleaning up temporary files failed, please manually delete %s"
msgstr "Не удалось удалить временные файлы, пожалуйста, удалите %s вручную"

#: ../pybackpack/gui.py:611
msgid "Restore succeeded.\n"
msgstr "Успешно восстановлено.\n"

#: ../pybackpack/gui.py:613
#, python-format
msgid ""
"Restore succeeded.\n"
"The restored files are in 'restored_files/%s' in your home directory."
msgstr ""
"Восстановление прошло успешно.\n"
"Восстановленные файлы находятся в 'restored_files/%s' в вашей домашней папке."

#: ../pybackpack/gui.py:657
msgid ""
"An error occurred while reading the remote backup set information.\n"
"Please check the username, host name and path that you have entered and try "
"again."
msgstr ""
"При чтении информации удаленного набора резервирования произошла ошибка.\n"
"Пожалуйста, проверьте введенные имя пользователя, узел и путь, и повторите "
"попытку."

#: ../pybackpack/gui.py:675
#, python-format
msgid "%s is a tool for backing up user data for the GNOME Desktop"
msgstr ""
"%s - это программа резервного копирования пользовательских данных для "
"рабочего стола GNOME"

#: ../pybackpack/gui.py:697
msgid "Copying from CD:"
msgstr "Копирование с CD:"

#: ../pybackpack/gui.py:708
#, python-format
msgid "Could not remove '%(filename)s': %(error_msg)s"
msgstr "Не удалось удалить '%(filename)s': %(error_msg)s"

#: ../pybackpack/gui.py:712
msgid "Operation failed.\n"
msgstr "Не удалось выполнить операцию.\n"

#: ../pybackpack/gui.py:717
msgid "Restore aborted, no files were changed.\n"
msgstr "Восстановление прервано, все файлы оставлены без изменений.\n"

#: ../pybackpack/rdiff_interface.py:178
msgid "Error:"
msgstr "Ошибка:"

#: ../pybackpack/rdiff_interface.py:179
msgid "rdiff-backup version: "
msgstr "версия rdiff-backup:"

#: ../pybackpack/rdiff_interface.py:180
msgid "version:"
msgstr "версия:"

#: ../pybackpack/seteditor.py:26
msgid "Unable to start the backup set editor"
msgstr "Не удалось запустить редактор наборов резервирования"

#: ../pybackpack/seteditor.py:56
msgid "Path"
msgstr "Путь"

#: ../pybackpack/seteditor.py:86 ../pybackpack/seteditor.glade:7
msgid "Create New Backup Set"
msgstr "Создать новый набор резервирования"

#: ../pybackpack/seteditor.py:105 ../pybackpack/seteditor.glade:940
msgid "0 items"
msgstr "0 объектов"

#: ../pybackpack/seteditor.py:176
#, python-format
msgid "Editing backup set '%s'"
msgstr "Редактируется набор резервирования '%s'"

#: ../pybackpack/seteditor.py:182
msgid "Editing new backup set"
msgstr ""

#: ../pybackpack/seteditor.py:218
#, python-format
msgid ""
"A set with the name '%s' already exists.\n"
"You can either enter a new name in the text box above, or overwrite the "
"existing set."
msgstr ""
"Уже существует резервная копия с именем '%s'.\n"
"Вы можете либо ввести новое имя в поле выше, либо заменить существующую "
"копию."

#: ../pybackpack/seteditor.py:250
#, python-format
msgid "Add Files/Folders to '%s'"
msgstr "Добавить файлы и папки в '%s'"

#: ../pybackpack/seteditor.py:256
msgid "You cannot create an empty backup set."
msgstr "Вы не можете создать пустой набор резервирования."

#: ../pybackpack/seteditor.py:283
msgid "Select a default destination"
msgstr "Выберите назначение по умолчанию"

#: ../pybackpack/seteditor.py:318
#, python-format
msgid "ERROR: Couldn't write new set %(name)s: %(error)s"
msgstr "ОШИБКА: Не удалось записать новый набор %(name)s: %(error)s"

#: ../pybackpack/seteditor.py:332 ../pybackpack/seteditor.py:348
#: ../pybackpack/seteditor.py:359
msgid "1 item"
msgstr "1 объект"

#: ../pybackpack/seteditor.py:334 ../pybackpack/seteditor.py:350
#: ../pybackpack/seteditor.py:361
#, python-format
msgid "%d items"
msgstr "%d объектов"

#: ../pybackpack/seteditor.py:369
msgid ""
"No CD burners available, because you do not have the python module "
"braseromedia."
msgstr ""

#: ../pybackpack/statuswindow.py:20
msgid "Failed to initialise status window."
msgstr "Не удалось инициализировать окно состояния."

#: ../pybackpack/filechooser.glade:6
msgid "Select backup destination"
msgstr "Выберите папку назначения для резервной копии"

#: ../pybackpack/gui.glade:20
msgid "_File"
msgstr "_Файл"

#: ../pybackpack/gui.glade:26
msgid "New _Backup Set..."
msgstr "Новая резервная _копия..."

#: ../pybackpack/gui.glade:42
msgid "_Restore From..."
msgstr "В_осстановить из..."

#: ../pybackpack/gui.glade:78
msgid "_View"
msgstr "_Вид"

#: ../pybackpack/gui.glade:84
msgid "_Status Window"
msgstr ""

#: ../pybackpack/gui.glade:104
msgid "_Help"
msgstr "_Справка"

#: ../pybackpack/gui.glade:158
msgid ""
"To backup your entire home directory to a blank CD or DVD, click the 'Go' "
"button. This backup will include all of your personal settings, documents, e-"
"mails and any other readable files stored in your home directory. For more "
"options or to backup a different set of files, click the tab labelled "
"'Backup' above."
msgstr ""
"Для создания полной резервной копии вашей домашней папки на CD или DVD "
"нажмите кнопку 'Начать'. В эту резервную копию будут включены ваши личные "
"настройки, документы, электронная почта и все файлы в вашей домашней папке, "
"которые могут быть прочитаны. Для изменения настроек или выборочного "
"копирования файлов выберите вкладку 'Резервная копия' выше."

#: ../pybackpack/gui.glade:196
msgid "Go"
msgstr "Начать"

#: ../pybackpack/gui.glade:221
msgid "<b>Home Directory Backup</b>"
msgstr "<b>Резервная копия домашней папки</b>"

#: ../pybackpack/gui.glade:247
msgid "Home"
msgstr "Домашняя папка"

#: ../pybackpack/gui.glade:336 ../pybackpack/gui.glade:1078
#: ../pybackpack/seteditor.glade:144 ../pybackpack/seteditor.glade:1052
msgid "Description:"
msgstr "Описание:"

#: ../pybackpack/gui.glade:366
msgid "<b>Backup set</b>"
msgstr ""

#: ../pybackpack/gui.glade:396 ../pybackpack/seteditor.glade:632
msgid ""
"Local File System\n"
"CD/DVD\n"
"Remote Host (SSH)"
msgstr ""
"Локальная файловая система\n"
"CD/DVD\n"
"Удаленный компьютер (SSH)"

#: ../pybackpack/gui.glade:421 ../pybackpack/seteditor.glade:1090
msgid "Destination:"
msgstr "Назначение:"

#: ../pybackpack/gui.glade:475
msgid "Removable media"
msgstr "Отсоединяемое устройство"

#: ../pybackpack/gui.glade:497 ../pybackpack/seteditor.glade:403
msgid "local"
msgstr "локально"

#: ../pybackpack/gui.glade:529 ../pybackpack/seteditor.glade:466
msgid "cd"
msgstr "cd"

#: ../pybackpack/gui.glade:548 ../pybackpack/seteditor.glade:485
msgid "Username:"
msgstr "Имя пользователя:"

#: ../pybackpack/gui.glade:559 ../pybackpack/seteditor.glade:496
msgid "Host:"
msgstr "Узел:"

#: ../pybackpack/gui.glade:572 ../pybackpack/seteditor.glade:509
msgid "Path:"
msgstr "Путь:"

#: ../pybackpack/gui.glade:658 ../pybackpack/seteditor.glade:600
msgid "ssh"
msgstr "ssh"

#: ../pybackpack/gui.glade:679
msgid "<b>Destination</b>"
msgstr ""

#: ../pybackpack/gui.glade:698
msgid "Show details"
msgstr "Показать подробности"

#: ../pybackpack/gui.glade:743
msgid "_Backup"
msgstr "Резервная _копия"

#: ../pybackpack/gui.glade:787
msgid "Backup"
msgstr "Резервная копия"

#: ../pybackpack/gui.glade:822
msgid "Local"
msgstr "Локально"

#: ../pybackpack/gui.glade:838
msgid "Remote (SSH)"
msgstr "Удаленно (SSH)"

#: ../pybackpack/gui.glade:860
msgid "Username"
msgstr "Имя пользователя"

#: ../pybackpack/gui.glade:862
msgid "username"
msgstr "пользователь"

#: ../pybackpack/gui.glade:876
msgid "Remote Hostname"
msgstr "Имя удаленного компьютера"

#: ../pybackpack/gui.glade:878
msgid "host"
msgstr "узел"

#: ../pybackpack/gui.glade:894
msgid "Refresh"
msgstr "Обновить"

#: ../pybackpack/gui.glade:972
msgid "<b>Location to restore from:</b>"
msgstr "<b>Восстановить из:</b>"

#: ../pybackpack/gui.glade:1009
msgid "Restore as of:"
msgstr "Восстановить копию от:"

#: ../pybackpack/gui.glade:1052
msgid ""
"Read-only\n"
"source"
msgstr ""
"исходные только\n"
"для чтения"

#: ../pybackpack/gui.glade:1092 ../pybackpack/seteditor.glade:668
#: ../pybackpack/seteditor.glade:1038
msgid "Name:"
msgstr "Название:"

#: ../pybackpack/gui.glade:1173
msgid "_Restore"
msgstr "В_осстановить"

#: ../pybackpack/gui.glade:1214
msgid "Restore"
msgstr "Восстановить"

#: ../pybackpack/seteditor.glade:21
msgid "New Backup Set"
msgstr "Новый набор резервирования"

#: ../pybackpack/seteditor.glade:22
msgid ""
"This guide will walk you through the steps\n"
"needed to create a group of files that are\n"
"backed up, known as a 'backup set'.\n"
"\n"
"Click 'Forward' to begin."
msgstr ""
"Этот помощник проведет вас через шаги,\n"
"необходимые для создания группы файлов\n"
"для резервного копирования, так называемый\n"
"\"набор резервирования\"\n"
"\n"
"Чтобы начать, нажмите 'Вперёд'."

#: ../pybackpack/seteditor.glade:32
msgid "Backup Set Name"
msgstr "Название набора резервирования"

#: ../pybackpack/seteditor.glade:51
msgid ""
"Enter a name for the new backup set.\n"
"e.g. \"e-mail\" for a set containing e-mail messages and settings."
msgstr ""
"Введите название набора резервирования.\n"
"Например, \"e-mail\" для копии писем и настроек электронной почты."

#: ../pybackpack/seteditor.glade:70
msgid "Enter some descriptive text for this new set."
msgstr "Введите описание для нового набора."

#: ../pybackpack/seteditor.glade:95
msgid ""
"A set with the name '' already exists.\n"
"You can either enter a new name in the text box above, or overwrite the "
"existing set."
msgstr ""
"Уже есть резервная копия с именем ''.\n"
"Вы можете либо ввести новое имя в поле вверху, либо заменить существующую "
"копию."

#: ../pybackpack/seteditor.glade:108
msgid "Overwrite existing set"
msgstr "Заменить существующую резервную копию"

#: ../pybackpack/seteditor.glade:126
msgid "<b>Warning</b>"
msgstr "<b>Предупреждение</b>"

#: ../pybackpack/seteditor.glade:167
msgid ""
"You didn't enter a name for this backup set.\n"
"Please enter a name in the relevant field above and click 'Forward' to "
"continue."
msgstr ""
"Вы не ввели имя набора резервирования.\n"
"Пожалуйста, введите имя в соответствующее поле вверху и нажмите 'Вперёд' для "
"продолжения."

#: ../pybackpack/seteditor.glade:183 ../pybackpack/seteditor.glade:227
#: ../pybackpack/seteditor.glade:270
msgid "<b>Error</b>"
msgstr "<b>Ошибка</b>"

#: ../pybackpack/seteditor.glade:211
msgid ""
"You selected to backup to a remote host, but didn't provide enough "
"information.\n"
"Please enter your username, remote host, and the absolute path where the "
"files should be backed up to."
msgstr ""
"Вы выбрали резервное копирование на удаленный компьютер, но не указали "
"достаточной информации.\n"
"Пожалуйста, введите имя пользователя, узел и полный путь для сохранения "
"резервных копий файлов."

#: ../pybackpack/seteditor.glade:255
msgid ""
"You do not have appropriate permissions to use the CD/DVD burner you have "
"selected '%s'."
msgstr ""
"У вас нет необходимых прав для использования выбранного CD/DVD привода '%s'."

#: ../pybackpack/seteditor.glade:308
msgid "Default Destination:"
msgstr "Путь по умолчанию:"

#: ../pybackpack/seteditor.glade:335
msgid ""
"[Optional]\n"
"Select a default location for this set to be backed up to."
msgstr ""
"[Желательно]\n"
"Выберите путь по умолчанию для резервных копий этого набора."

#: ../pybackpack/seteditor.glade:346
msgid "This is a removable device"
msgstr "Сменное устройство"

#: ../pybackpack/seteditor.glade:416
msgid "Select which CD/DVD Burner to use:"
msgstr "Укажите, какой привод CD/DVD использовать:"

#: ../pybackpack/seteditor.glade:427
msgid "CD/DVD Burner:"
msgstr "Привод CD/DVD:"

#: ../pybackpack/seteditor.glade:620
msgid "Destination type:"
msgstr "Тип назначения:"

#: ../pybackpack/seteditor.glade:658
msgid ""
"This new backup set needs to be given a name, and optionally, a description "
"and a default destination for backups made from this set."
msgstr ""
"Новому набору файлов нужно дать имя и, желательно, описание и путь "
"назначения по умолчанию для создания резервных копий."

#: ../pybackpack/seteditor.glade:679
msgid "Click 'Forward' to continue."
msgstr "Для продолжения нажмите 'Вперёд'."

#: ../pybackpack/seteditor.glade:707
msgid ""
"To add a file/folder to the backup set, select it in the file chooser and "
"click 'Add to set'."
msgstr ""
"Для добавления файла или папки в набор резервирования выберите их в окне "
"выбора файлов и нажмите 'Включить в набор'."

#: ../pybackpack/seteditor.glade:737
msgid "Show hidden files"
msgstr "Показать скрытые файлы"

#: ../pybackpack/seteditor.glade:775
msgid "Exclude from set"
msgstr "Исключить из набора"

#: ../pybackpack/seteditor.glade:824
msgid "Include in set"
msgstr "Включить в набор"

#: ../pybackpack/seteditor.glade:912
msgid "Remove from set"
msgstr "Удалить из набора"

#: ../pybackpack/seteditor.glade:963
msgid "Summary"
msgstr "Сводка"

#: ../pybackpack/seteditor.glade:980
msgid ""
"This page gives you an opportunity to review the backup set before it is "
"saved.\n"
"To make any changes, click 'Back'."
msgstr ""
"Эта страница дает вам возможность проверить настройки для выбранного набора "
"файлов перед их сохранением.\n"
"Для изменения настроек нажмите 'Назад'."

#: ../pybackpack/seteditor.glade:1011
msgid "To proceed and save this backup set, click 'Forward'."
msgstr "Для применения настроек и сохранения шаблона нажмите 'Вперёд'."

#: ../pybackpack/seteditor.glade:1024
msgid "Files:"
msgstr "Файлы:"

#: ../pybackpack/seteditor.glade:1120
msgid "Finished!"
msgstr "Завершено!"

#: ../pybackpack/seteditor.glade:1121
msgid "You're all done! Congratulations."
msgstr "Всё готово! Поздравляем."

#: ../pybackpack/statuswindow.glade:8
msgid "Backup Status Window"
msgstr "Статус резервного копирования"

#: ../pybackpack/statuswindow.glade:48
msgid "<b>Status</b>"
msgstr "<b>Статус</b>"

#~ msgid "Backup Sets"
#~ msgstr "Наборы резервирования"

#~ msgid ""
#~ "To begin, you need to create a new backup set. Click the 'New' button to "
#~ "get started."
#~ msgstr ""
#~ "Для начала вам нужно создать новый набор резервирования. Для этого "
#~ "нажмите на кнопку 'Создать'."

#~ msgid "To begin, select a backup set from the list on the left."
#~ msgstr "Чтобы начать, выберите набор резервирования из списка слева."

#~ msgid "<b>Description</b>"
#~ msgstr "<b>Описание</b>"

#~ msgid "CD/DVD Progress"
#~ msgstr "Прогресс CD/DVD"

#~ msgid "<b><big>Writing CD/DVD</big></b>"
#~ msgstr "<b><big>Записывается CD/DVD</big></b>"

#~ msgid "<i>Burning data...</i>"
#~ msgstr "<i>Записываются данные...</i>"

#~ msgid ""
#~ "No CD burners available, because you do not have the python module "
#~ "nautilusburn."
#~ msgstr ""
#~ "Пишущие CD приводы недоступны из-за того, что у вас не установлен модуль "
#~ "python nautilusburn."

#~ msgid "No CD burners were detected on your system."
#~ msgstr "Системой не обнаружены пишущие дисководы."

#~ msgid "Select which CD burner to use:"
#~ msgstr "Выберите устройство для записи диска:"

#~ msgid "Please insert a blank CD into %s"
#~ msgstr "Пожалуйста, вставьте чистый диск в %s"

#~ msgid "To restore your data, select the folder that contains the backup."
#~ msgstr "Для восстановления данных выберите папку с резервной копией."

#~ msgid "very strange"
#~ msgstr "очень странно"

#~ msgid "Location is:"
#~ msgstr "Расположение:"
